#ifndef _DIGITALOUTPUT_H_
#define _DIGITALOUTPUT_H_

/* Generated by WriteClassHeaderVisitor: Thu Jul 12 2018 16:00:52 GMT-0600 (MDT) */

typedef struct _PhidgetDigitalOutput *PhidgetDigitalOutputHandle;

/* Methods */
API_PRETURN_HDR PhidgetDigitalOutput_create(PhidgetDigitalOutputHandle *ch);
API_PRETURN_HDR PhidgetDigitalOutput_delete(PhidgetDigitalOutputHandle *ch);

/* Properties */
API_PRETURN_HDR PhidgetDigitalOutput_setDutyCycle(PhidgetDigitalOutputHandle ch, double dutyCycle);
API_VRETURN_HDR PhidgetDigitalOutput_setDutyCycle_async(PhidgetDigitalOutputHandle ch, double dutyCycle,
  Phidget_AsyncCallback fptr, void *ctx);
API_PRETURN_HDR PhidgetDigitalOutput_getDutyCycle(PhidgetDigitalOutputHandle ch, double *dutyCycle);
API_PRETURN_HDR PhidgetDigitalOutput_getMinDutyCycle(PhidgetDigitalOutputHandle ch,
  double *minDutyCycle);
API_PRETURN_HDR PhidgetDigitalOutput_getMaxDutyCycle(PhidgetDigitalOutputHandle ch,
  double *maxDutyCycle);
API_PRETURN_HDR PhidgetDigitalOutput_setLEDCurrentLimit(PhidgetDigitalOutputHandle ch,
  double LEDCurrentLimit);
API_VRETURN_HDR PhidgetDigitalOutput_setLEDCurrentLimit_async(PhidgetDigitalOutputHandle ch,
  double LEDCurrentLimit, Phidget_AsyncCallback fptr, void *ctx);
API_PRETURN_HDR PhidgetDigitalOutput_getLEDCurrentLimit(PhidgetDigitalOutputHandle ch,
  double *LEDCurrentLimit);
API_PRETURN_HDR PhidgetDigitalOutput_getMinLEDCurrentLimit(PhidgetDigitalOutputHandle ch,
  double *minLEDCurrentLimit);
API_PRETURN_HDR PhidgetDigitalOutput_getMaxLEDCurrentLimit(PhidgetDigitalOutputHandle ch,
  double *maxLEDCurrentLimit);
API_PRETURN_HDR PhidgetDigitalOutput_setLEDForwardVoltage(PhidgetDigitalOutputHandle ch,
  PhidgetDigitalOutput_LEDForwardVoltage LEDForwardVoltage);
API_PRETURN_HDR PhidgetDigitalOutput_getLEDForwardVoltage(PhidgetDigitalOutputHandle ch,
  PhidgetDigitalOutput_LEDForwardVoltage *LEDForwardVoltage);
API_PRETURN_HDR PhidgetDigitalOutput_setState(PhidgetDigitalOutputHandle ch, int state);
API_VRETURN_HDR PhidgetDigitalOutput_setState_async(PhidgetDigitalOutputHandle ch, int state,
  Phidget_AsyncCallback fptr, void *ctx);
API_PRETURN_HDR PhidgetDigitalOutput_getState(PhidgetDigitalOutputHandle ch, int *state);

/* Events */

#endif /* _DIGITALOUTPUT_H_ */
