#ifndef _SPATIAL_H_
#define _SPATIAL_H_

/* Generated by WriteClassHeaderVisitor: Thu Jul 12 2018 16:00:52 GMT-0600 (MDT) */

typedef struct _PhidgetSpatial *PhidgetSpatialHandle;

/* Methods */
API_PRETURN_HDR PhidgetSpatial_create(PhidgetSpatialHandle *ch);
API_PRETURN_HDR PhidgetSpatial_delete(PhidgetSpatialHandle *ch);
API_PRETURN_HDR PhidgetSpatial_setMagnetometerCorrectionParameters(PhidgetSpatialHandle ch,
  double magneticField, double offset0, double offset1, double offset2, double gain0, double gain1, double gain2, double T0, double T1, double T2, double T3, double T4, double T5);
API_PRETURN_HDR PhidgetSpatial_resetMagnetometerCorrectionParameters(PhidgetSpatialHandle ch);
API_PRETURN_HDR PhidgetSpatial_saveMagnetometerCorrectionParameters(PhidgetSpatialHandle ch);
API_PRETURN_HDR PhidgetSpatial_zeroGyro(PhidgetSpatialHandle ch);

/* Properties */
API_PRETURN_HDR PhidgetSpatial_setDataInterval(PhidgetSpatialHandle ch, uint32_t dataInterval);
API_PRETURN_HDR PhidgetSpatial_getDataInterval(PhidgetSpatialHandle ch, uint32_t *dataInterval);
API_PRETURN_HDR PhidgetSpatial_getMinDataInterval(PhidgetSpatialHandle ch, uint32_t *minDataInterval);
API_PRETURN_HDR PhidgetSpatial_getMaxDataInterval(PhidgetSpatialHandle ch, uint32_t *maxDataInterval);

/* Events */
typedef void (CCONV *PhidgetSpatial_OnSpatialDataCallback)(PhidgetSpatialHandle ch, void *ctx,
  const double acceleration[3], const double angularRate[3], const double magneticField[3], double timestamp);

API_PRETURN_HDR PhidgetSpatial_setOnSpatialDataHandler(PhidgetSpatialHandle ch,
  PhidgetSpatial_OnSpatialDataCallback fptr, void *ctx);

#endif /* _SPATIAL_H_ */
